name: portofolio_app
description: A Very Good Project created by Very Good CLI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  appwrite: ^12.0.1
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_3d_controller: ^1.2.1
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  need_resume: ^1.0.7+1
  open_street_map_search_and_pick: ^0.1.1
  rive: ^0.12.4
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.0
  supercharged: ^2.1.1
  uuid: ^4.3.3
  flutter_local_notifications: ^8.2.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  mockito: ^5.0.16

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
