// Mocks generated by Mockito 5.4.4 from annotations
// in portofolio_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:appwrite/appwrite.dart' as _i5;
import 'package:appwrite/enums.dart' as _i16;
import 'package:appwrite/models.dart' as _i6;
import 'package:appwrite/src/enums.dart' as _i18;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:portofolio_app/core/error/failure.dart' as _i9;
import 'package:portofolio_app/core/parameter/create_param.dart' as _i11;
import 'package:portofolio_app/features/home/data/datasources/remote/rumah_data_source.dart'
    as _i7;
import 'package:portofolio_app/features/home/data/models/rumah_model.dart'
    as _i2;
import 'package:portofolio_app/features/home/domain/entities/rumah_entity.dart'
    as _i10;
import 'package:portofolio_app/features/home/domain/repositories/home_page_repositories.dart'
    as _i4;
import 'package:portofolio_app/features/home/domain/usecases/delete_track_usecase.dart'
    as _i12;
import 'package:portofolio_app/features/home/domain/usecases/get_data_home_usecase.dart'
    as _i13;
import 'package:portofolio_app/features/home/domain/usecases/set_rumah_usecase.dart'
    as _i14;
import 'package:portofolio_app/features/home/domain/usecases/update_track_usecase.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRumahModel_0 extends _i1.SmartFake implements _i2.RumahModel {
  _FakeRumahModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomePageRepo_2 extends _i1.SmartFake implements _i4.HomePageRepo {
  _FakeHomePageRepo_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_3 extends _i1.SmartFake implements _i5.Client {
  _FakeClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_4 extends _i1.SmartFake implements _i6.User {
  _FakeUser_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIdentityList_5 extends _i1.SmartFake implements _i6.IdentityList {
  _FakeIdentityList_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJwt_6 extends _i1.SmartFake implements _i6.Jwt {
  _FakeJwt_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogList_7 extends _i1.SmartFake implements _i6.LogList {
  _FakeLogList_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaType_8 extends _i1.SmartFake implements _i6.MfaType {
  _FakeMfaType_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaChallenge_9 extends _i1.SmartFake implements _i6.MfaChallenge {
  _FakeMfaChallenge_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaFactors_10 extends _i1.SmartFake implements _i6.MfaFactors {
  _FakeMfaFactors_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMfaRecoveryCodes_11 extends _i1.SmartFake
    implements _i6.MfaRecoveryCodes {
  _FakeMfaRecoveryCodes_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreferences_12 extends _i1.SmartFake implements _i6.Preferences {
  _FakePreferences_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToken_13 extends _i1.SmartFake implements _i6.Token {
  _FakeToken_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSessionList_14 extends _i1.SmartFake implements _i6.SessionList {
  _FakeSessionList_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSession_15 extends _i1.SmartFake implements _i6.Session {
  _FakeSession_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTarget_16 extends _i1.SmartFake implements _i6.Target {
  _FakeTarget_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_17<T> extends _i1.SmartFake implements _i5.Response<T> {
  _FakeResponse_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentList_18 extends _i1.SmartFake implements _i6.DocumentList {
  _FakeDocumentList_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocument_19 extends _i1.SmartFake implements _i6.Document {
  _FakeDocument_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RumahDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRumahDataSource extends _i1.Mock implements _i7.RumahDataSource {
  MockRumahDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> createRumahData(_i2.RumahModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRumahData,
          [params],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.RumahModel>> getAllRumahData() => (super.noSuchMethod(
        Invocation.method(
          #getAllRumahData,
          [],
        ),
        returnValue: _i8.Future<List<_i2.RumahModel>>.value(<_i2.RumahModel>[]),
      ) as _i8.Future<List<_i2.RumahModel>>);

  @override
  _i8.Future<_i2.RumahModel> getDocument(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [documentId],
        ),
        returnValue: _i8.Future<_i2.RumahModel>.value(_FakeRumahModel_0(
          this,
          Invocation.method(
            #getDocument,
            [documentId],
          ),
        )),
      ) as _i8.Future<_i2.RumahModel>);

  @override
  _i8.Future<bool> deleteDocument(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [documentId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> updateDocument(_i2.RumahModel? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [params],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [HomePageRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomePageRepo extends _i1.Mock implements _i4.HomePageRepo {
  MockHomePageRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.Either<_i9.Failure, List<_i10.RumahEntity>>>
      getHomePageData() => (super.noSuchMethod(
            Invocation.method(
              #getHomePageData,
              [],
            ),
            returnValue: _i8
                .Future<_i3.Either<_i9.Failure, List<_i10.RumahEntity>>>.value(
                _FakeEither_1<_i9.Failure, List<_i10.RumahEntity>>(
              this,
              Invocation.method(
                #getHomePageData,
                [],
              ),
            )),
          ) as _i8.Future<_i3.Either<_i9.Failure, List<_i10.RumahEntity>>>);

  @override
  _i8.Future<_i3.Either<_i9.Failure, String>> setRumahData(
          _i11.CreateParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRumahData,
          [params],
        ),
        returnValue: _i8.Future<_i3.Either<_i9.Failure, String>>.value(
            _FakeEither_1<_i9.Failure, String>(
          this,
          Invocation.method(
            #setRumahData,
            [params],
          ),
        )),
      ) as _i8.Future<_i3.Either<_i9.Failure, String>>);

  @override
  _i8.Future<_i3.Either<_i9.Failure, String>> deleteRumahData(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRumahData,
          [id],
        ),
        returnValue: _i8.Future<_i3.Either<_i9.Failure, String>>.value(
            _FakeEither_1<_i9.Failure, String>(
          this,
          Invocation.method(
            #deleteRumahData,
            [id],
          ),
        )),
      ) as _i8.Future<_i3.Either<_i9.Failure, String>>);

  @override
  _i8.Future<_i3.Either<_i9.Failure, String>> updateRumahData(
          _i10.RumahEntity? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRumahData,
          [params],
        ),
        returnValue: _i8.Future<_i3.Either<_i9.Failure, String>>.value(
            _FakeEither_1<_i9.Failure, String>(
          this,
          Invocation.method(
            #updateRumahData,
            [params],
          ),
        )),
      ) as _i8.Future<_i3.Either<_i9.Failure, String>>);
}

/// A class which mocks [DeleteTrackUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTrackUseCase extends _i1.Mock
    implements _i12.DeleteTrackUseCase {
  MockDeleteTrackUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.HomePageRepo get homePageRepo => (super.noSuchMethod(
        Invocation.getter(#homePageRepo),
        returnValue: _FakeHomePageRepo_2(
          this,
          Invocation.getter(#homePageRepo),
        ),
      ) as _i4.HomePageRepo);

  @override
  _i8.Future<_i3.Either<_i9.Failure, String>> call({String? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i8.Future<_i3.Either<_i9.Failure, String>>.value(
            _FakeEither_1<_i9.Failure, String>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i8.Future<_i3.Either<_i9.Failure, String>>);
}

/// A class which mocks [GetDataHomeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDataHomeUseCase extends _i1.Mock
    implements _i13.GetDataHomeUseCase {
  MockGetDataHomeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.HomePageRepo get homePageRepo => (super.noSuchMethod(
        Invocation.getter(#homePageRepo),
        returnValue: _FakeHomePageRepo_2(
          this,
          Invocation.getter(#homePageRepo),
        ),
      ) as _i4.HomePageRepo);

  @override
  _i8.Future<_i3.Either<_i9.Failure, List<_i10.RumahEntity>>> call(
          {dynamic params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i8.Future<_i3.Either<_i9.Failure, List<_i10.RumahEntity>>>.value(
                _FakeEither_1<_i9.Failure, List<_i10.RumahEntity>>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i8.Future<_i3.Either<_i9.Failure, List<_i10.RumahEntity>>>);
}

/// A class which mocks [SetRumahUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetRumahUseCase extends _i1.Mock implements _i14.SetRumahUseCase {
  MockSetRumahUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.HomePageRepo get homePageRepo => (super.noSuchMethod(
        Invocation.getter(#homePageRepo),
        returnValue: _FakeHomePageRepo_2(
          this,
          Invocation.getter(#homePageRepo),
        ),
      ) as _i4.HomePageRepo);

  @override
  _i8.Future<_i3.Either<_i9.Failure, String>> call(
          {_i11.CreateParam? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i8.Future<_i3.Either<_i9.Failure, String>>.value(
            _FakeEither_1<_i9.Failure, String>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i8.Future<_i3.Either<_i9.Failure, String>>);
}

/// A class which mocks [UpdateTrackUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTrackUseCase extends _i1.Mock
    implements _i15.UpdateTrackUseCase {
  MockUpdateTrackUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.HomePageRepo get homePageRepo => (super.noSuchMethod(
        Invocation.getter(#homePageRepo),
        returnValue: _FakeHomePageRepo_2(
          this,
          Invocation.getter(#homePageRepo),
        ),
      ) as _i4.HomePageRepo);

  @override
  _i8.Future<_i3.Either<_i9.Failure, String>> call(
          {_i10.RumahEntity? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i8.Future<_i3.Either<_i9.Failure, String>>.value(
            _FakeEither_1<_i9.Failure, String>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i8.Future<_i3.Either<_i9.Failure, String>>);
}

/// A class which mocks [Account].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccount extends _i1.Mock implements _i5.Account {
  MockAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_3(
          this,
          Invocation.getter(#client),
        ),
      ) as _i5.Client);

  @override
  _i8.Future<_i6.User> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #get,
            [],
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.User> create({
    required String? userId,
    required String? email,
    required String? password,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #userId: userId,
            #email: email,
            #password: password,
            #name: name,
          },
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #create,
            [],
            {
              #userId: userId,
              #email: email,
              #password: password,
              #name: name,
            },
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.User> updateEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #updateEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.IdentityList> listIdentities({List<String>? queries}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listIdentities,
          [],
          {#queries: queries},
        ),
        returnValue: _i8.Future<_i6.IdentityList>.value(_FakeIdentityList_5(
          this,
          Invocation.method(
            #listIdentities,
            [],
            {#queries: queries},
          ),
        )),
      ) as _i8.Future<_i6.IdentityList>);

  @override
  _i8.Future<dynamic> deleteIdentity({required String? identityId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIdentity,
          [],
          {#identityId: identityId},
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<_i6.Jwt> createJWT() => (super.noSuchMethod(
        Invocation.method(
          #createJWT,
          [],
        ),
        returnValue: _i8.Future<_i6.Jwt>.value(_FakeJwt_6(
          this,
          Invocation.method(
            #createJWT,
            [],
          ),
        )),
      ) as _i8.Future<_i6.Jwt>);

  @override
  _i8.Future<_i6.LogList> listLogs({List<String>? queries}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLogs,
          [],
          {#queries: queries},
        ),
        returnValue: _i8.Future<_i6.LogList>.value(_FakeLogList_7(
          this,
          Invocation.method(
            #listLogs,
            [],
            {#queries: queries},
          ),
        )),
      ) as _i8.Future<_i6.LogList>);

  @override
  _i8.Future<_i6.User> updateMFA({required bool? mfa}) => (super.noSuchMethod(
        Invocation.method(
          #updateMFA,
          [],
          {#mfa: mfa},
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #updateMFA,
            [],
            {#mfa: mfa},
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.MfaType> createMfaAuthenticator(
          {required _i16.AuthenticatorType? type}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMfaAuthenticator,
          [],
          {#type: type},
        ),
        returnValue: _i8.Future<_i6.MfaType>.value(_FakeMfaType_8(
          this,
          Invocation.method(
            #createMfaAuthenticator,
            [],
            {#type: type},
          ),
        )),
      ) as _i8.Future<_i6.MfaType>);

  @override
  _i8.Future<_i6.User> updateMfaAuthenticator({
    required _i16.AuthenticatorType? type,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMfaAuthenticator,
          [],
          {
            #type: type,
            #otp: otp,
          },
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #updateMfaAuthenticator,
            [],
            {
              #type: type,
              #otp: otp,
            },
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.User> deleteMfaAuthenticator({
    required _i16.AuthenticatorType? type,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMfaAuthenticator,
          [],
          {
            #type: type,
            #otp: otp,
          },
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #deleteMfaAuthenticator,
            [],
            {
              #type: type,
              #otp: otp,
            },
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.MfaChallenge> createMfaChallenge(
          {required _i16.AuthenticationFactor? factor}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMfaChallenge,
          [],
          {#factor: factor},
        ),
        returnValue: _i8.Future<_i6.MfaChallenge>.value(_FakeMfaChallenge_9(
          this,
          Invocation.method(
            #createMfaChallenge,
            [],
            {#factor: factor},
          ),
        )),
      ) as _i8.Future<_i6.MfaChallenge>);

  @override
  _i8.Future<dynamic> updateMfaChallenge({
    required String? challengeId,
    required String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMfaChallenge,
          [],
          {
            #challengeId: challengeId,
            #otp: otp,
          },
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<_i6.MfaFactors> listMfaFactors() => (super.noSuchMethod(
        Invocation.method(
          #listMfaFactors,
          [],
        ),
        returnValue: _i8.Future<_i6.MfaFactors>.value(_FakeMfaFactors_10(
          this,
          Invocation.method(
            #listMfaFactors,
            [],
          ),
        )),
      ) as _i8.Future<_i6.MfaFactors>);

  @override
  _i8.Future<_i6.MfaRecoveryCodes> getMfaRecoveryCodes() => (super.noSuchMethod(
        Invocation.method(
          #getMfaRecoveryCodes,
          [],
        ),
        returnValue:
            _i8.Future<_i6.MfaRecoveryCodes>.value(_FakeMfaRecoveryCodes_11(
          this,
          Invocation.method(
            #getMfaRecoveryCodes,
            [],
          ),
        )),
      ) as _i8.Future<_i6.MfaRecoveryCodes>);

  @override
  _i8.Future<_i6.MfaRecoveryCodes> createMfaRecoveryCodes() =>
      (super.noSuchMethod(
        Invocation.method(
          #createMfaRecoveryCodes,
          [],
        ),
        returnValue:
            _i8.Future<_i6.MfaRecoveryCodes>.value(_FakeMfaRecoveryCodes_11(
          this,
          Invocation.method(
            #createMfaRecoveryCodes,
            [],
          ),
        )),
      ) as _i8.Future<_i6.MfaRecoveryCodes>);

  @override
  _i8.Future<_i6.MfaRecoveryCodes> updateMfaRecoveryCodes() =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMfaRecoveryCodes,
          [],
        ),
        returnValue:
            _i8.Future<_i6.MfaRecoveryCodes>.value(_FakeMfaRecoveryCodes_11(
          this,
          Invocation.method(
            #updateMfaRecoveryCodes,
            [],
          ),
        )),
      ) as _i8.Future<_i6.MfaRecoveryCodes>);

  @override
  _i8.Future<_i6.User> updateName({required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateName,
          [],
          {#name: name},
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #updateName,
            [],
            {#name: name},
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.User> updatePassword({
    required String? password,
    String? oldPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [],
          {
            #password: password,
            #oldPassword: oldPassword,
          },
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #updatePassword,
            [],
            {
              #password: password,
              #oldPassword: oldPassword,
            },
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.User> updatePhone({
    required String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhone,
          [],
          {
            #phone: phone,
            #password: password,
          },
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #updatePhone,
            [],
            {
              #phone: phone,
              #password: password,
            },
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.Preferences> getPrefs() => (super.noSuchMethod(
        Invocation.method(
          #getPrefs,
          [],
        ),
        returnValue: _i8.Future<_i6.Preferences>.value(_FakePreferences_12(
          this,
          Invocation.method(
            #getPrefs,
            [],
          ),
        )),
      ) as _i8.Future<_i6.Preferences>);

  @override
  _i8.Future<_i6.User> updatePrefs({required Map<dynamic, dynamic>? prefs}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePrefs,
          [],
          {#prefs: prefs},
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #updatePrefs,
            [],
            {#prefs: prefs},
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.Token> createRecovery({
    required String? email,
    required String? url,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRecovery,
          [],
          {
            #email: email,
            #url: url,
          },
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_13(
          this,
          Invocation.method(
            #createRecovery,
            [],
            {
              #email: email,
              #url: url,
            },
          ),
        )),
      ) as _i8.Future<_i6.Token>);

  @override
  _i8.Future<_i6.Token> updateRecovery({
    required String? userId,
    required String? secret,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecovery,
          [],
          {
            #userId: userId,
            #secret: secret,
            #password: password,
          },
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_13(
          this,
          Invocation.method(
            #updateRecovery,
            [],
            {
              #userId: userId,
              #secret: secret,
              #password: password,
            },
          ),
        )),
      ) as _i8.Future<_i6.Token>);

  @override
  _i8.Future<_i6.SessionList> listSessions() => (super.noSuchMethod(
        Invocation.method(
          #listSessions,
          [],
        ),
        returnValue: _i8.Future<_i6.SessionList>.value(_FakeSessionList_14(
          this,
          Invocation.method(
            #listSessions,
            [],
          ),
        )),
      ) as _i8.Future<_i6.SessionList>);

  @override
  _i8.Future<dynamic> deleteSessions() => (super.noSuchMethod(
        Invocation.method(
          #deleteSessions,
          [],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<_i6.Session> createAnonymousSession() => (super.noSuchMethod(
        Invocation.method(
          #createAnonymousSession,
          [],
        ),
        returnValue: _i8.Future<_i6.Session>.value(_FakeSession_15(
          this,
          Invocation.method(
            #createAnonymousSession,
            [],
          ),
        )),
      ) as _i8.Future<_i6.Session>);

  @override
  _i8.Future<_i6.Session> createEmailPasswordSession({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEmailPasswordSession,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i8.Future<_i6.Session>.value(_FakeSession_15(
          this,
          Invocation.method(
            #createEmailPasswordSession,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i8.Future<_i6.Session>);

  @override
  _i8.Future<_i6.Session> updateMagicURLSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMagicURLSession,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i8.Future<_i6.Session>.value(_FakeSession_15(
          this,
          Invocation.method(
            #updateMagicURLSession,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i8.Future<_i6.Session>);

  @override
  _i8.Future<dynamic> createOAuth2Session({
    required _i16.OAuthProvider? provider,
    String? success,
    String? failure,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOAuth2Session,
          [],
          {
            #provider: provider,
            #success: success,
            #failure: failure,
            #scopes: scopes,
          },
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<_i6.Session> updatePhoneSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneSession,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i8.Future<_i6.Session>.value(_FakeSession_15(
          this,
          Invocation.method(
            #updatePhoneSession,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i8.Future<_i6.Session>);

  @override
  _i8.Future<_i6.Session> createSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSession,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i8.Future<_i6.Session>.value(_FakeSession_15(
          this,
          Invocation.method(
            #createSession,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i8.Future<_i6.Session>);

  @override
  _i8.Future<_i6.Session> getSession({required String? sessionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSession,
          [],
          {#sessionId: sessionId},
        ),
        returnValue: _i8.Future<_i6.Session>.value(_FakeSession_15(
          this,
          Invocation.method(
            #getSession,
            [],
            {#sessionId: sessionId},
          ),
        )),
      ) as _i8.Future<_i6.Session>);

  @override
  _i8.Future<_i6.Session> updateSession({required String? sessionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [],
          {#sessionId: sessionId},
        ),
        returnValue: _i8.Future<_i6.Session>.value(_FakeSession_15(
          this,
          Invocation.method(
            #updateSession,
            [],
            {#sessionId: sessionId},
          ),
        )),
      ) as _i8.Future<_i6.Session>);

  @override
  _i8.Future<dynamic> deleteSession({required String? sessionId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSession,
          [],
          {#sessionId: sessionId},
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<_i6.User> updateStatus() => (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [],
        ),
        returnValue: _i8.Future<_i6.User>.value(_FakeUser_4(
          this,
          Invocation.method(
            #updateStatus,
            [],
          ),
        )),
      ) as _i8.Future<_i6.User>);

  @override
  _i8.Future<_i6.Target> createPushTarget({
    required String? targetId,
    required String? identifier,
    String? providerId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPushTarget,
          [],
          {
            #targetId: targetId,
            #identifier: identifier,
            #providerId: providerId,
          },
        ),
        returnValue: _i8.Future<_i6.Target>.value(_FakeTarget_16(
          this,
          Invocation.method(
            #createPushTarget,
            [],
            {
              #targetId: targetId,
              #identifier: identifier,
              #providerId: providerId,
            },
          ),
        )),
      ) as _i8.Future<_i6.Target>);

  @override
  _i8.Future<_i6.Target> updatePushTarget({
    required String? targetId,
    required String? identifier,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePushTarget,
          [],
          {
            #targetId: targetId,
            #identifier: identifier,
          },
        ),
        returnValue: _i8.Future<_i6.Target>.value(_FakeTarget_16(
          this,
          Invocation.method(
            #updatePushTarget,
            [],
            {
              #targetId: targetId,
              #identifier: identifier,
            },
          ),
        )),
      ) as _i8.Future<_i6.Target>);

  @override
  _i8.Future<dynamic> deletePushTarget({required String? targetId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePushTarget,
          [],
          {#targetId: targetId},
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<_i6.Token> createEmailToken({
    required String? userId,
    required String? email,
    bool? phrase,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEmailToken,
          [],
          {
            #userId: userId,
            #email: email,
            #phrase: phrase,
          },
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_13(
          this,
          Invocation.method(
            #createEmailToken,
            [],
            {
              #userId: userId,
              #email: email,
              #phrase: phrase,
            },
          ),
        )),
      ) as _i8.Future<_i6.Token>);

  @override
  _i8.Future<_i6.Token> createMagicURLToken({
    required String? userId,
    required String? email,
    String? url,
    bool? phrase,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMagicURLToken,
          [],
          {
            #userId: userId,
            #email: email,
            #url: url,
            #phrase: phrase,
          },
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_13(
          this,
          Invocation.method(
            #createMagicURLToken,
            [],
            {
              #userId: userId,
              #email: email,
              #url: url,
              #phrase: phrase,
            },
          ),
        )),
      ) as _i8.Future<_i6.Token>);

  @override
  _i8.Future<dynamic> createOAuth2Token({
    required _i16.OAuthProvider? provider,
    String? success,
    String? failure,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOAuth2Token,
          [],
          {
            #provider: provider,
            #success: success,
            #failure: failure,
            #scopes: scopes,
          },
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<_i6.Token> createPhoneToken({
    required String? userId,
    required String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPhoneToken,
          [],
          {
            #userId: userId,
            #phone: phone,
          },
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_13(
          this,
          Invocation.method(
            #createPhoneToken,
            [],
            {
              #userId: userId,
              #phone: phone,
            },
          ),
        )),
      ) as _i8.Future<_i6.Token>);

  @override
  _i8.Future<_i6.Token> createVerification({required String? url}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVerification,
          [],
          {#url: url},
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_13(
          this,
          Invocation.method(
            #createVerification,
            [],
            {#url: url},
          ),
        )),
      ) as _i8.Future<_i6.Token>);

  @override
  _i8.Future<_i6.Token> updateVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVerification,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_13(
          this,
          Invocation.method(
            #updateVerification,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i8.Future<_i6.Token>);

  @override
  _i8.Future<_i6.Token> createPhoneVerification() => (super.noSuchMethod(
        Invocation.method(
          #createPhoneVerification,
          [],
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_13(
          this,
          Invocation.method(
            #createPhoneVerification,
            [],
          ),
        )),
      ) as _i8.Future<_i6.Token>);

  @override
  _i8.Future<_i6.Token> updatePhoneVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneVerification,
          [],
          {
            #userId: userId,
            #secret: secret,
          },
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_13(
          this,
          Invocation.method(
            #updatePhoneVerification,
            [],
            {
              #userId: userId,
              #secret: secret,
            },
          ),
        )),
      ) as _i8.Future<_i6.Token>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i5.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  set config(Map<String, String>? _config) => super.noSuchMethod(
        Invocation.setter(
          #config,
          _config,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get endPoint => (super.noSuchMethod(
        Invocation.getter(#endPoint),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#endPoint),
        ),
      ) as String);

  @override
  _i8.Future<dynamic> webAuth(
    Uri? url, {
    String? callbackUrlScheme,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #webAuth,
          [url],
          {#callbackUrlScheme: callbackUrlScheme},
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<_i5.Response<dynamic>> chunkedUpload({
    required String? path,
    required Map<String, dynamic>? params,
    required String? paramName,
    required String? idParamName,
    required Map<String, String>? headers,
    dynamic Function(_i5.UploadProgress)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chunkedUpload,
          [],
          {
            #path: path,
            #params: params,
            #paramName: paramName,
            #idParamName: idParamName,
            #headers: headers,
            #onProgress: onProgress,
          },
        ),
        returnValue:
            _i8.Future<_i5.Response<dynamic>>.value(_FakeResponse_17<dynamic>(
          this,
          Invocation.method(
            #chunkedUpload,
            [],
            {
              #path: path,
              #params: params,
              #paramName: paramName,
              #idParamName: idParamName,
              #headers: headers,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i8.Future<_i5.Response<dynamic>>);

  @override
  _i5.Client setSelfSigned({bool? status = true}) => (super.noSuchMethod(
        Invocation.method(
          #setSelfSigned,
          [],
          {#status: status},
        ),
        returnValue: _FakeClient_3(
          this,
          Invocation.method(
            #setSelfSigned,
            [],
            {#status: status},
          ),
        ),
      ) as _i5.Client);

  @override
  _i5.Client setEndpoint(String? endPoint) => (super.noSuchMethod(
        Invocation.method(
          #setEndpoint,
          [endPoint],
        ),
        returnValue: _FakeClient_3(
          this,
          Invocation.method(
            #setEndpoint,
            [endPoint],
          ),
        ),
      ) as _i5.Client);

  @override
  _i5.Client setEndPointRealtime(String? endPoint) => (super.noSuchMethod(
        Invocation.method(
          #setEndPointRealtime,
          [endPoint],
        ),
        returnValue: _FakeClient_3(
          this,
          Invocation.method(
            #setEndPointRealtime,
            [endPoint],
          ),
        ),
      ) as _i5.Client);

  @override
  _i5.Client setProject(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #setProject,
          [value],
        ),
        returnValue: _FakeClient_3(
          this,
          Invocation.method(
            #setProject,
            [value],
          ),
        ),
      ) as _i5.Client);

  @override
  _i5.Client setJWT(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #setJWT,
          [value],
        ),
        returnValue: _FakeClient_3(
          this,
          Invocation.method(
            #setJWT,
            [value],
          ),
        ),
      ) as _i5.Client);

  @override
  _i5.Client setLocale(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [value],
        ),
        returnValue: _FakeClient_3(
          this,
          Invocation.method(
            #setLocale,
            [value],
          ),
        ),
      ) as _i5.Client);

  @override
  _i5.Client setSession(dynamic value) => (super.noSuchMethod(
        Invocation.method(
          #setSession,
          [value],
        ),
        returnValue: _FakeClient_3(
          this,
          Invocation.method(
            #setSession,
            [value],
          ),
        ),
      ) as _i5.Client);

  @override
  _i5.Client addHeader(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHeader,
          [
            key,
            value,
          ],
        ),
        returnValue: _FakeClient_3(
          this,
          Invocation.method(
            #addHeader,
            [
              key,
              value,
            ],
          ),
        ),
      ) as _i5.Client);

  @override
  _i8.Future<_i5.Response<dynamic>> call(
    _i18.HttpMethod? method, {
    String? path = r'',
    Map<String, String>? headers = const {},
    Map<String, dynamic>? params = const {},
    _i18.ResponseType? responseType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [method],
          {
            #path: path,
            #headers: headers,
            #params: params,
            #responseType: responseType,
          },
        ),
        returnValue:
            _i8.Future<_i5.Response<dynamic>>.value(_FakeResponse_17<dynamic>(
          this,
          Invocation.method(
            #call,
            [method],
            {
              #path: path,
              #headers: headers,
              #params: params,
              #responseType: responseType,
            },
          ),
        )),
      ) as _i8.Future<_i5.Response<dynamic>>);
}

/// A class which mocks [Databases].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabases extends _i1.Mock implements _i5.Databases {
  MockDatabases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_3(
          this,
          Invocation.getter(#client),
        ),
      ) as _i5.Client);

  @override
  _i8.Future<_i6.DocumentList> listDocuments({
    required String? databaseId,
    required String? collectionId,
    List<String>? queries,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listDocuments,
          [],
          {
            #databaseId: databaseId,
            #collectionId: collectionId,
            #queries: queries,
          },
        ),
        returnValue: _i8.Future<_i6.DocumentList>.value(_FakeDocumentList_18(
          this,
          Invocation.method(
            #listDocuments,
            [],
            {
              #databaseId: databaseId,
              #collectionId: collectionId,
              #queries: queries,
            },
          ),
        )),
      ) as _i8.Future<_i6.DocumentList>);

  @override
  _i8.Future<_i6.Document> createDocument({
    required String? databaseId,
    required String? collectionId,
    required String? documentId,
    required Map<dynamic, dynamic>? data,
    List<String>? permissions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDocument,
          [],
          {
            #databaseId: databaseId,
            #collectionId: collectionId,
            #documentId: documentId,
            #data: data,
            #permissions: permissions,
          },
        ),
        returnValue: _i8.Future<_i6.Document>.value(_FakeDocument_19(
          this,
          Invocation.method(
            #createDocument,
            [],
            {
              #databaseId: databaseId,
              #collectionId: collectionId,
              #documentId: documentId,
              #data: data,
              #permissions: permissions,
            },
          ),
        )),
      ) as _i8.Future<_i6.Document>);

  @override
  _i8.Future<_i6.Document> getDocument({
    required String? databaseId,
    required String? collectionId,
    required String? documentId,
    List<String>? queries,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [],
          {
            #databaseId: databaseId,
            #collectionId: collectionId,
            #documentId: documentId,
            #queries: queries,
          },
        ),
        returnValue: _i8.Future<_i6.Document>.value(_FakeDocument_19(
          this,
          Invocation.method(
            #getDocument,
            [],
            {
              #databaseId: databaseId,
              #collectionId: collectionId,
              #documentId: documentId,
              #queries: queries,
            },
          ),
        )),
      ) as _i8.Future<_i6.Document>);

  @override
  _i8.Future<_i6.Document> updateDocument({
    required String? databaseId,
    required String? collectionId,
    required String? documentId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [],
          {
            #databaseId: databaseId,
            #collectionId: collectionId,
            #documentId: documentId,
            #data: data,
            #permissions: permissions,
          },
        ),
        returnValue: _i8.Future<_i6.Document>.value(_FakeDocument_19(
          this,
          Invocation.method(
            #updateDocument,
            [],
            {
              #databaseId: databaseId,
              #collectionId: collectionId,
              #documentId: documentId,
              #data: data,
              #permissions: permissions,
            },
          ),
        )),
      ) as _i8.Future<_i6.Document>);

  @override
  _i8.Future<dynamic> deleteDocument({
    required String? databaseId,
    required String? collectionId,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [],
          {
            #databaseId: databaseId,
            #collectionId: collectionId,
            #documentId: documentId,
          },
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
}

/// A class which mocks [Document].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocument extends _i1.Mock implements _i6.Document {
  MockDocument() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get $id => (super.noSuchMethod(
        Invocation.getter(#$id),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#$id),
        ),
      ) as String);

  @override
  String get $collectionId => (super.noSuchMethod(
        Invocation.getter(#$collectionId),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#$collectionId),
        ),
      ) as String);

  @override
  String get $databaseId => (super.noSuchMethod(
        Invocation.getter(#$databaseId),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#$databaseId),
        ),
      ) as String);

  @override
  String get $createdAt => (super.noSuchMethod(
        Invocation.getter(#$createdAt),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#$createdAt),
        ),
      ) as String);

  @override
  String get $updatedAt => (super.noSuchMethod(
        Invocation.getter(#$updatedAt),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#$updatedAt),
        ),
      ) as String);

  @override
  List<dynamic> get $permissions => (super.noSuchMethod(
        Invocation.getter(#$permissions),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  Map<String, dynamic> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  T convertTo<T>(T Function(Map<dynamic, dynamic>)? fromJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertTo,
          [fromJson],
        ),
        returnValue: _i17.dummyValue<T>(
          this,
          Invocation.method(
            #convertTo,
            [fromJson],
          ),
        ),
      ) as T);
}
